---
title: "tutorial"
author: "Jinxuan Yao, Liwen Peng"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(class)
library(randomForest)
library(knitr)
library(kableExtra)
```

```{r}
# load data
my_penguins <- read.csv('/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Data/my_penguins.csv')
my_gapminder <- read.csv('/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Data/my_gapminder.csv')
```

```{r}
## A tutorial for my_rf_cv
my_rf_cv <- source("/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Code/my_rf_cv.R")
my_rf_cv <- as.function(my_rf_cv[[1]])
# iterate when k = 2
k <- 2
MSE_k2 <- rep(NA,30)
for(i in 1:30){
  MSE_k2[i] = my_rf_cv(k)
}
```

```{r}
# iterate when k = 5
k <- 5
MSE_k5 <- rep(NA,30)
for(i in 1:30){
  MSE_k5[i] = my_rf_cv(k)
}
```

```{r}
# iterate when k = 10
k <- 10
MSE_k10 <- rep(NA,30)
for(i in 1:30){
  MSE_k10[i] = my_rf_cv(k)
}
```

```{r}
# make a dataframe
MSE_k2_df <- data.frame(cv_error = MSE_k2, k = 2)

# make a dataframe
MSE_k5_df <- data.frame(cv_error = MSE_k5, k = 5)

# make a dataframe
MSE_k10_df <- data.frame(cv_error = MSE_k10, k = 10)

# combine a matrix with full data
MSE_fulldata <- cbind(MSE_k2, MSE_k5, MSE_k10)

colnames(MSE_fulldata) <- c("k = 2", "k = 5", "k = 10")
MSE_fulldata <- data.frame(MSE_fulldata)

# save it to results fold
write_csv(MSE_fulldata,
          path ="/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Output/Results/SimResults.csv")
```

```{r}
k_2_5_10_boxplot <-ggplot(MSE_k2_df, aes(k, cv_error)) + 
                  geom_boxplot() +
                  geom_boxplot(data = MSE_k5_df) +
                  geom_boxplot(data = MSE_k10_df) +
                  theme_bw(base_size = 12) +
                  labs(x = "k", y = "Cross-validation Error")

ggsave(filename = "k_2_5_10_boxplot.pdf", 
       plot = k_2_5_10_boxplot,
       path = "/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Output/Figures")
```

```{r}
# calculate the mean and sd when k = 2
mean_mse_k2 <- mean(MSE_k2_df$cv_error)
sd_mse_k2 <- sd(MSE_k2_df$cv_error)

# calculate the mean and sd when k = 5
mean_mse_k5 <- mean(MSE_k5_df$cv_error)
sd_mse_k5 <- sd(MSE_k5_df$cv_error)

# calculate the mean and sd when k = 10
mean_mse_k10 <- mean(MSE_k10_df$cv_error)
sd_mse_k10 <- sd(MSE_k10_df$cv_error)

# make a matrix
mse_k2_5_10_matrix <- matrix(c(mean_mse_k2, sd_mse_k2, mean_mse_k5,                        sd_mse_k5, mean_mse_k10, sd_mse_k10),
                       nrow = 3,
                       ncol = 2,
                       byrow = TRUE
                       )
# name the rows and cols of the matrix
rownames(mse_k2_5_10_matrix) <- c("k=2","k=5","k=10")
colnames(mse_k2_5_10_matrix) <- c("mean","sd")
# make a table
my_table <- kable_styling(kable(mse_k2_5_10_matrix))
my_table
saveRDS(my_table, 
        file ="/Users/yaojinxuan/Desktop/STAT302/Projects/Project_2/Project2pipeline/Output/Results/mean_sd_results.RDS")
```
From the plot and the table, we can find that mean mse decreases as k increases, and sd also decreases as k increases. I think it is because as k increases, the amount of training data increases for every single iteration, thus the mean mse decreases.  
